---
apiVersion: v1
kind: Service
metadata:
  name: azurite-blob
  namespace: az-mocks
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "azurite"
  ports:
  - name: http
    port: 80
    targetPort: 10000
...
---
apiVersion: v1
kind: Service
metadata:
  name: azurite-queue
  namespace: az-mocks
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "azurite"
  ports:
  - name: http
    port: 80
    targetPort: 10001
...
---
apiVersion: v1
kind: Service
metadata:
  name: azurite-table
  namespace: az-mocks
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "azurite"
  ports:
  - name: http
    port: 80
    targetPort: 10002
...